"""Generate src/edinet/models/edinet_code.py from EdinetcodeDlInfo.csv."""
from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Any


EXPECTED_HEADERS = [
    "ＥＤＩＮＥＴコード",
    "提出者種別",
    "上場区分",
    "連結の有無",
    "資本金",
    "決算日",
    "提出者名",
    "提出者名（英字）",
    "提出者名（ヨミ）",
    "所在地",
    "提出者業種",
    "証券コード",
    "提出者法人番号",
]


def _norm_text(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _to_py_str(value: str | None) -> str:
    return "None" if value is None else repr(value)


def _to_py_int(value: int | None) -> str:
    return "None" if value is None else str(value)


def _parse_capital_million_yen(value: str | None) -> int | None:
    if value is None:
        return None
    normalized = value.replace(",", "").replace("，", "").strip()
    if not normalized:
        return None
    return int(normalized)


def _normalize_row(row: list[str], header_len: int, name_en_idx: int) -> list[str]:
    if len(row) == header_len:
        return row
    if len(row) < header_len:
        return row + [""] * (header_len - len(row))

    # Some rows include commas in submitter_name_en; merge overflow columns there.
    extra = len(row) - header_len
    merged_name_en = ",".join(row[name_en_idx : name_en_idx + extra + 1])
    fixed = row[:name_en_idx] + [merged_name_en] + row[name_en_idx + extra + 1 :]
    if len(fixed) != header_len:
        raise ValueError(
            f"Failed to normalize row length: original={len(row)} normalized={len(fixed)}"
        )
    return fixed


def load_edinet_records(source: Path) -> list[dict[str, str | int | None]]:
    with source.open("r", encoding="cp932", newline="") as fp:
        reader = csv.reader(fp)
        # metadata row
        next(reader, None)
        header = next(reader, None)
        if header is None:
            raise ValueError("EdinetcodeDlInfo.csv: missing header row.")

        header = [_norm_text(col) or "" for col in header]
        if header != EXPECTED_HEADERS:
            raise ValueError(
                "Unexpected header row in EdinetcodeDlInfo.csv.\n"
                f"Expected: {EXPECTED_HEADERS}\n"
                f"Actual:   {header}"
            )
        idx = {name: i for i, name in enumerate(header)}
        name_en_idx = idx["提出者名（英字）"]

        records: list[dict[str, str | int | None]] = []
        seen_codes: set[str] = set()
        for raw_row in reader:
            if not raw_row:
                continue
            row = _normalize_row(raw_row, len(header), name_en_idx)

            edinet_code = _norm_text(row[idx["ＥＤＩＮＥＴコード"]])
            if edinet_code is None:
                continue
            if edinet_code in seen_codes:
                raise ValueError(f"Duplicate edinet_code: {edinet_code}")
            seen_codes.add(edinet_code)

            records.append(
                {
                    "edinet_code": edinet_code,
                    "submitter_type": _norm_text(row[idx["提出者種別"]]) or "",
                    "listing_status": _norm_text(row[idx["上場区分"]]),
                    "consolidated": _norm_text(row[idx["連結の有無"]]),
                    "capital_million_yen": _parse_capital_million_yen(
                        _norm_text(row[idx["資本金"]])
                    ),
                    "fiscal_year_end": _norm_text(row[idx["決算日"]]),
                    "submitter_name": _norm_text(row[idx["提出者名"]]) or "",
                    "submitter_name_en": _norm_text(row[idx["提出者名（英字）"]]),
                    "submitter_name_yomi": _norm_text(row[idx["提出者名（ヨミ）"]]),
                    "address": _norm_text(row[idx["所在地"]]),
                    "industry": _norm_text(row[idx["提出者業種"]]),
                    "sec_code": _norm_text(row[idx["証券コード"]]),
                    "corporate_number": _norm_text(row[idx["提出者法人番号"]]),
                }
            )

    records.sort(key=lambda rec: rec["edinet_code"] or "")
    return records


def render_edinet_module(
    records: list[dict[str, str | int | None]], source_name: str
) -> str:
    lines: list[str] = []
    lines.append('"""EDINETコード (edinetCode) のモデル定義。')
    lines.append("")
    lines.append("AUTO-GENERATED by tools/generate_edinet_codes.py. DO NOT EDIT.")
    lines.append(f"Source: {source_name}")
    lines.append('"""')
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("import warnings")
    lines.append("")
    lines.append("from pydantic import BaseModel, ConfigDict")
    lines.append("")
    lines.append("from edinet.exceptions import EdinetWarning")
    lines.append("")
    lines.append("")
    lines.append("class EdinetCodeEntry(BaseModel):")
    lines.append('    """EDINETコードリストの1行。"""')
    lines.append("")
    lines.append("    model_config = ConfigDict(frozen=True)")
    lines.append("")
    lines.append("    edinet_code: str")
    lines.append("    submitter_type: str")
    lines.append("    listing_status: str | None")
    lines.append("    consolidated: str | None")
    lines.append("    capital_million_yen: int | None")
    lines.append("    fiscal_year_end: str | None")
    lines.append("    submitter_name: str")
    lines.append("    submitter_name_en: str | None")
    lines.append("    submitter_name_yomi: str | None")
    lines.append("    address: str | None")
    lines.append("    industry: str | None")
    lines.append("    sec_code: str | None")
    lines.append("    corporate_number: str | None")
    lines.append("")
    lines.append("    def __str__(self) -> str:")
    lines.append(
        '        return f"EdinetCodeEntry({self.edinet_code} | {self.submitter_name} | {self.sec_code})"'
    )
    lines.append("")
    lines.append("")
    lines.append("_EDINET_CODE_TABLE: dict[str, EdinetCodeEntry] = {")
    for rec in records:
        code = rec["edinet_code"] or ""
        lines.append(f"    {_to_py_str(code)}: EdinetCodeEntry(")
        lines.append(f"        edinet_code={_to_py_str(code)},")
        lines.append(f"        submitter_type={_to_py_str(rec['submitter_type'])},")
        lines.append(f"        listing_status={_to_py_str(rec['listing_status'])},")
        lines.append(f"        consolidated={_to_py_str(rec['consolidated'])},")
        lines.append(
            f"        capital_million_yen={_to_py_int(rec['capital_million_yen'])},"
        )
        lines.append(f"        fiscal_year_end={_to_py_str(rec['fiscal_year_end'])},")
        lines.append(f"        submitter_name={_to_py_str(rec['submitter_name'])},")
        lines.append(f"        submitter_name_en={_to_py_str(rec['submitter_name_en'])},")
        lines.append(
            f"        submitter_name_yomi={_to_py_str(rec['submitter_name_yomi'])},"
        )
        lines.append(f"        address={_to_py_str(rec['address'])},")
        lines.append(f"        industry={_to_py_str(rec['industry'])},")
        lines.append(f"        sec_code={_to_py_str(rec['sec_code'])},")
        lines.append(f"        corporate_number={_to_py_str(rec['corporate_number'])},")
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    lines.append("EDINET_CODE_RECORD_COUNT = len(_EDINET_CODE_TABLE)")
    lines.append("")
    lines.append("_warned_unknown_edinet_codes: set[str] = set()")
    lines.append("")
    lines.append("")
    lines.append("def get_edinet_code(code: str) -> EdinetCodeEntry | None:")
    lines.append('    """EDINETコードから EdinetCodeEntry を返す。"""')
    lines.append("    entry = _EDINET_CODE_TABLE.get(code)")
    lines.append("    if entry is None and code not in _warned_unknown_edinet_codes:")
    lines.append("        _warned_unknown_edinet_codes.add(code)")
    lines.append("        warnings.warn(")
    lines.append('            f"Unknown edinetCode: {code!r}.",')
    lines.append("            category=EdinetWarning,")
    lines.append("            stacklevel=2,")
    lines.append("        )")
    lines.append("    return entry")
    lines.append("")
    lines.append("")
    lines.append("def all_edinet_codes() -> list[EdinetCodeEntry]:")
    lines.append('    """全EDINETコードの一覧を返す。"""')
    lines.append("    return list(_EDINET_CODE_TABLE.values())")

    # --- 検索ヘルパー関数 ---

    # (1) _normalize_sec_code
    lines.append("")
    lines.append("")
    lines.append("def _normalize_sec_code(sec_code: str) -> str:")
    lines.append('    """証券コードを5桁に正規化する。')
    lines.append("")
    lines.append("    Args:")
    lines.append("        sec_code: 証券コード（4桁または5桁）。")
    lines.append("")
    lines.append("    Returns:")
    lines.append("        5桁に正規化された証券コード。")
    lines.append('    """')
    lines.append("    sec_code = sec_code.strip()")
    lines.append("    if len(sec_code) == 4:")
    lines.append('        return sec_code + "0"')
    lines.append("    return sec_code")

    # (2) _match_rank
    lines.append("")
    lines.append("")
    lines.append("def _match_rank(entry: EdinetCodeEntry, query_lower: str) -> int:")
    lines.append('    """エントリと検索クエリのマッチ度を返す。')
    lines.append("")
    lines.append("    Returns:")
    lines.append("        0: submitter_name が query で始まる（最優先）")
    lines.append("        1: submitter_name_en が query で始まる（case-insensitive）")
    lines.append("        2: submitter_name_yomi が query で始まる")
    lines.append("        3: いずれかのフィールドに query を含む（部分一致）")
    lines.append("        -1: マッチしない")
    lines.append('    """')
    lines.append("    name_lower = entry.submitter_name.lower()")
    lines.append("    if name_lower.startswith(query_lower):")
    lines.append("        return 0")
    lines.append("    name_en_lower = entry.submitter_name_en.lower() if entry.submitter_name_en else None")
    lines.append("    if name_en_lower and name_en_lower.startswith(query_lower):")
    lines.append("        return 1")
    lines.append("    name_yomi_lower = entry.submitter_name_yomi.lower() if entry.submitter_name_yomi else None")
    lines.append("    if name_yomi_lower and name_yomi_lower.startswith(query_lower):")
    lines.append("        return 2")
    lines.append("    if query_lower in name_lower:")
    lines.append("        return 3")
    lines.append("    if name_en_lower and query_lower in name_en_lower:")
    lines.append("        return 3")
    lines.append("    if name_yomi_lower and query_lower in name_yomi_lower:")
    lines.append("        return 3")
    lines.append("    return -1")

    # (3) search_edinet_codes
    lines.append("")
    lines.append("")
    lines.append("def search_edinet_codes(")
    lines.append("    query: str,")
    lines.append("    *,")
    lines.append("    limit: int = 20,")
    lines.append(") -> list[EdinetCodeEntry]:")
    lines.append('    """企業名でEdinetCodeEntryを部分一致検索する。')
    lines.append("")
    lines.append("    ``submitter_name`` / ``submitter_name_en`` / ``submitter_name_yomi`` の")
    lines.append("    いずれかに ``query`` が含まれるエントリを返す。大文字・小文字を区別しない。")
    lines.append("")
    lines.append("    結果は関連度順にソートされる:")
    lines.append("    - 名前が query で始まるもの（prefix match）が先頭")
    lines.append("    - 名前に query を含むもの（contains match）が後続")
    lines.append("")
    lines.append("    Args:")
    lines.append("        query: 検索キーワード。空文字の場合は空リストを返す。")
    lines.append("        limit: 最大返却件数。0で無制限。")
    lines.append("")
    lines.append("    Returns:")
    lines.append("        マッチしたEdinetCodeEntryのリスト（関連度順）。")
    lines.append('    """')
    lines.append("    if not query:")
    lines.append("        return []")
    lines.append("    query_lower = query.lower()")
    lines.append("    ranked: list[tuple[int, EdinetCodeEntry]] = []")
    lines.append("    for entry in all_edinet_codes():")
    lines.append("        rank = _match_rank(entry, query_lower)")
    lines.append("        if rank >= 0:")
    lines.append("            ranked.append((rank, entry))")
    lines.append("    ranked.sort(key=lambda t: t[0])")
    lines.append("    results = [entry for _, entry in ranked]")
    lines.append("    if limit > 0:")
    lines.append("        results = results[:limit]")
    lines.append("    return results")

    # (4) get_edinet_code_by_sec_code
    lines.append("")
    lines.append("")
    lines.append("def get_edinet_code_by_sec_code(sec_code: str) -> EdinetCodeEntry | None:")
    lines.append('    """証券コードからEdinetCodeEntryを返す。')
    lines.append("")
    lines.append('    4桁の場合は末尾に ``"0"`` を付与して5桁にしてから検索する。')
    lines.append("")
    lines.append("    Args:")
    lines.append("        sec_code: 証券コード（4桁または5桁）。")
    lines.append("")
    lines.append("    Returns:")
    lines.append("        マッチしたEdinetCodeEntry。見つからない場合はNone。")
    lines.append('    """')
    lines.append("    normalized = _normalize_sec_code(sec_code)")
    lines.append("    for entry in all_edinet_codes():")
    lines.append("        if entry.sec_code == normalized:")
    lines.append("            return entry")
    lines.append("    return None")

    # (5) get_edinet_codes_by_industry
    lines.append("")
    lines.append("")
    lines.append("def get_edinet_codes_by_industry(")
    lines.append("    industry: str,")
    lines.append("    *,")
    lines.append("    limit: int = 100,")
    lines.append(") -> list[EdinetCodeEntry]:")
    lines.append('    """業種名でEdinetCodeEntryを検索する。')
    lines.append("")
    lines.append("    ``industry`` フィールドの完全一致で検索する。")
    lines.append("")
    lines.append("    Args:")
    lines.append('        industry: 業種名（例: ``"輸送用機器"``）。')
    lines.append("        limit: 最大返却件数。0で無制限。")
    lines.append("")
    lines.append("    Returns:")
    lines.append("        マッチしたEdinetCodeEntryのリスト。")
    lines.append('    """')
    lines.append("    results: list[EdinetCodeEntry] = []")
    lines.append("    for entry in all_edinet_codes():")
    lines.append("        if entry.industry == industry:")
    lines.append("            results.append(entry)")
    lines.append("            if limit > 0 and len(results) >= limit:")
    lines.append("                break")
    lines.append("    return results")

    # (6) get_listed_edinet_codes
    lines.append("")
    lines.append("")
    lines.append("def get_listed_edinet_codes(*, limit: int = 0) -> list[EdinetCodeEntry]:")
    lines.append('    """上場企業のEdinetCodeEntry一覧を返す。')
    lines.append("")
    lines.append('    ``listing_status == "上場"`` のエントリを返す。')
    lines.append("")
    lines.append("    Args:")
    lines.append("        limit: 最大返却件数。0で無制限。")
    lines.append("")
    lines.append("    Returns:")
    lines.append("        上場企業のEdinetCodeEntryのリスト。")
    lines.append('    """')
    lines.append("    results: list[EdinetCodeEntry] = []")
    lines.append("    for entry in all_edinet_codes():")
    lines.append('        if entry.listing_status == "上場":')
    lines.append("            results.append(entry)")
    lines.append("            if limit > 0 and len(results) >= limit:")
    lines.append("                break")
    lines.append("    return results")

    # --- 検索ヘルパー関数ここまで ---

    lines.append("")
    lines.append("")
    lines.append("def _reset_warning_state() -> None:")
    lines.append('    """テスト用。"""')
    lines.append("    _warned_unknown_edinet_codes.clear()")
    lines.append("")
    return "\n".join(lines)


def generate(source: Path, output: Path) -> int:
    records = load_edinet_records(source)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_edinet_module(records, source.as_posix()), encoding="utf-8")
    return len(records)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("data/source/EdinetcodeDlInfo.csv"),
        help="Path to EdinetcodeDlInfo.csv",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/edinet/models/edinet_code.py"),
        help="Path to generated edinet_code.py",
    )
    args = parser.parse_args()

    count = generate(args.source, args.output)
    print(f"Generated {args.output} with {count} records.")


if __name__ == "__main__":
    main()
