"""Generate src/edinet/models/fund_code.py from FundcodeDlInfo.csv."""
from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Any


EXPECTED_HEADERS = [
    "ファンドコード",
    "証券コード",
    "ファンド名",
    "ファンド名（ヨミ）",
    "特定有価証券区分名",
    "特定期1",
    "特定期2",
    "ＥＤＩＮＥＴコード",
    "発行者名",
]


def _norm_text(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _to_py(value: str | None) -> str:
    return "None" if value is None else repr(value)


def load_fund_records(source: Path) -> list[dict[str, str | None]]:
    with source.open("r", encoding="cp932", newline="") as fp:
        reader = csv.reader(fp)
        # metadata row
        next(reader, None)
        header = next(reader, None)
        if header is None:
            raise ValueError("FundcodeDlInfo.csv: missing header row.")

        header = [_norm_text(col) or "" for col in header]
        if header != EXPECTED_HEADERS:
            raise ValueError(
                "Unexpected header row in FundcodeDlInfo.csv.\n"
                f"Expected: {EXPECTED_HEADERS}\n"
                f"Actual:   {header}"
            )
        idx = {name: i for i, name in enumerate(header)}

        records: list[dict[str, str | None]] = []
        seen_fund_codes: set[str] = set()
        for row in reader:
            if not row:
                continue

            fund_code = _norm_text(row[idx["ファンドコード"]])
            if fund_code is None:
                continue
            if fund_code in seen_fund_codes:
                raise ValueError(f"Duplicate fund_code: {fund_code}")
            seen_fund_codes.add(fund_code)

            records.append(
                {
                    "fund_code": fund_code,
                    "sec_code": _norm_text(row[idx["証券コード"]]),
                    "fund_name": _norm_text(row[idx["ファンド名"]]) or "",
                    "fund_name_yomi": _norm_text(row[idx["ファンド名（ヨミ）"]]) or "",
                    "security_type": _norm_text(row[idx["特定有価証券区分名"]]) or "",
                    "period_1": _norm_text(row[idx["特定期1"]]),
                    "period_2": _norm_text(row[idx["特定期2"]]),
                    "edinet_code": _norm_text(row[idx["ＥＤＩＮＥＴコード"]]) or "",
                    "issuer_name": _norm_text(row[idx["発行者名"]]) or "",
                }
            )

    records.sort(key=lambda rec: rec["fund_code"] or "")
    return records


def render_fund_module(records: list[dict[str, str | None]], source_name: str) -> str:
    lines: list[str] = []
    lines.append('"""ファンドコード (fundCode) のモデル定義。')
    lines.append("")
    lines.append("AUTO-GENERATED by tools/generate_fund_codes.py. DO NOT EDIT.")
    lines.append(f"Source: {source_name}")
    lines.append('"""')
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("import warnings")
    lines.append("")
    lines.append("from pydantic import BaseModel, ConfigDict")
    lines.append("")
    lines.append("from edinet.exceptions import EdinetWarning")
    lines.append("")
    lines.append("")
    lines.append("class FundCodeEntry(BaseModel):")
    lines.append('    """ファンドコードリストの1行。"""')
    lines.append("")
    lines.append("    model_config = ConfigDict(frozen=True)")
    lines.append("")
    lines.append("    fund_code: str")
    lines.append("    sec_code: str | None")
    lines.append("    fund_name: str")
    lines.append("    fund_name_yomi: str")
    lines.append("    security_type: str")
    lines.append("    period_1: str | None")
    lines.append("    period_2: str | None")
    lines.append("    edinet_code: str")
    lines.append("    issuer_name: str")
    lines.append("")
    lines.append("    def __str__(self) -> str:")
    lines.append('        return f"FundCodeEntry({self.fund_code} | {self.fund_name})"')
    lines.append("")
    lines.append("")
    lines.append("_FUND_CODE_TABLE: dict[str, FundCodeEntry] = {")
    for rec in records:
        fund_code = rec["fund_code"] or ""
        lines.append(f"    {_to_py(fund_code)}: FundCodeEntry(")
        lines.append(f"        fund_code={_to_py(fund_code)},")
        lines.append(f"        sec_code={_to_py(rec['sec_code'])},")
        lines.append(f"        fund_name={_to_py(rec['fund_name'])},")
        lines.append(f"        fund_name_yomi={_to_py(rec['fund_name_yomi'])},")
        lines.append(f"        security_type={_to_py(rec['security_type'])},")
        lines.append(f"        period_1={_to_py(rec['period_1'])},")
        lines.append(f"        period_2={_to_py(rec['period_2'])},")
        lines.append(f"        edinet_code={_to_py(rec['edinet_code'])},")
        lines.append(f"        issuer_name={_to_py(rec['issuer_name'])},")
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    lines.append("FUND_CODE_RECORD_COUNT = len(_FUND_CODE_TABLE)")
    lines.append("")
    lines.append("_warned_unknown_fund_codes: set[str] = set()")
    lines.append("")
    lines.append("")
    lines.append("def get_fund_code(code: str) -> FundCodeEntry | None:")
    lines.append('    """ファンドコードから FundCodeEntry を返す。"""')
    lines.append("    entry = _FUND_CODE_TABLE.get(code)")
    lines.append("    if entry is None and code not in _warned_unknown_fund_codes:")
    lines.append("        _warned_unknown_fund_codes.add(code)")
    lines.append("        warnings.warn(")
    lines.append('            f"Unknown fundCode: {code!r}.",')
    lines.append("            category=EdinetWarning,")
    lines.append("            stacklevel=2,")
    lines.append("        )")
    lines.append("    return entry")
    lines.append("")
    lines.append("")
    lines.append("def all_fund_codes() -> list[FundCodeEntry]:")
    lines.append('    """全ファンドコードの一覧を返す。"""')
    lines.append("    return list(_FUND_CODE_TABLE.values())")
    lines.append("")
    lines.append("")
    lines.append("def _reset_warning_state() -> None:")
    lines.append('    """テスト用。"""')
    lines.append("    _warned_unknown_fund_codes.clear()")
    lines.append("")
    return "\n".join(lines)


def generate(source: Path, output: Path) -> int:
    records = load_fund_records(source)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_fund_module(records, source.as_posix()), encoding="utf-8")
    return len(records)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("data/source/FundcodeDlInfo.csv"),
        help="Path to FundcodeDlInfo.csv",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/edinet/models/fund_code.py"),
        help="Path to generated fund_code.py",
    )
    args = parser.parse_args()

    count = generate(args.source, args.output)
    print(f"Generated {args.output} with {count} records.")


if __name__ == "__main__":
    main()
