"""Generate src/edinet/models/form_code.py from ESE140327.xlsx."""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from openpyxl import load_workbook


EXPECTED_HEADERS = [
    "府令コード",
    "様式コード（コード値）",
    "様式番号",
    "様式名",
    "書類種別",
    "開示区分",
    "備考",
]


def _norm_header(value: str | None) -> str:
    if value is None:
        return ""
    return "".join(str(value).split())


def _norm_text(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _to_py(value: str | None) -> str:
    return "None" if value is None else repr(value)


def load_form_records(source: Path) -> list[dict[str, str | None]]:
    wb = load_workbook(source, read_only=True, data_only=True)
    ws = wb["様式コードリスト"]

    header_row = 3
    actual_headers = [
        _norm_text(ws.cell(row=header_row, column=2 + offset).value) or ""
        for offset in range(7)
    ]
    if [_norm_header(h) for h in actual_headers] != [_norm_header(h) for h in EXPECTED_HEADERS]:
        raise ValueError(
            "Unexpected header row in ESE140327.xlsx.\n"
            f"Expected: {EXPECTED_HEADERS}\n"
            f"Actual:   {actual_headers}"
        )

    records: list[dict[str, str | None]] = []
    seen_keys: set[tuple[str, str]] = set()
    for row in ws.iter_rows(min_row=4, min_col=2, max_col=8, values_only=True):
        ordinance_code = _norm_text(row[0])
        form_code = _norm_text(row[1])
        form_number = _norm_text(row[2])
        form_name = _norm_text(row[3])
        doc_type_name = _norm_text(row[4])
        disclosure_type = _norm_text(row[5])
        note = _norm_text(row[6])

        if ordinance_code is None and form_code is None:
            continue
        if ordinance_code is None or form_code is None:
            raise ValueError(
                "Found incomplete row in ESE140327.xlsx: "
                f"ordinance_code={ordinance_code!r}, form_code={form_code!r}"
            )

        key = (ordinance_code, form_code)
        if key in seen_keys:
            raise ValueError(f"Duplicate (ordinance_code, form_code): {key}")
        seen_keys.add(key)

        records.append(
            {
                "ordinance_code": ordinance_code,
                "form_code": form_code,
                "form_number": form_number or "",
                "form_name": form_name or "",
                "doc_type_name": doc_type_name or "",
                "disclosure_type": disclosure_type or "",
                "note": note,
            }
        )

    records.sort(key=lambda rec: (rec["ordinance_code"] or "", rec["form_code"] or ""))
    return records


def render_form_module(records: list[dict[str, str | None]], source_name: str) -> str:
    lines: list[str] = []
    lines.append('"""様式コード (formCode) のモデル定義。')
    lines.append("")
    lines.append("AUTO-GENERATED by tools/generate_form_codes.py. DO NOT EDIT.")
    lines.append(f"Source: {source_name}")
    lines.append('"""')
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("import warnings")
    lines.append("")
    lines.append("from pydantic import BaseModel, ConfigDict")
    lines.append("")
    lines.append("from edinet.exceptions import EdinetWarning")
    lines.append("")
    lines.append("")
    lines.append("class FormCodeEntry(BaseModel):")
    lines.append('    """様式コードリストの1行。"""')
    lines.append("")
    lines.append("    model_config = ConfigDict(frozen=True)")
    lines.append("")
    lines.append("    ordinance_code: str")
    lines.append("    form_code: str")
    lines.append("    form_number: str")
    lines.append("    form_name: str")
    lines.append("    doc_type_name: str")
    lines.append("    disclosure_type: str")
    lines.append("    note: str | None = None")
    lines.append("")
    lines.append("    def __str__(self) -> str:")
    lines.append(
        '        return f"FormCodeEntry({self.ordinance_code}/{self.form_code} | {self.form_name})"'
    )
    lines.append("")
    lines.append("")
    lines.append("_FORM_CODE_TABLE: dict[tuple[str, str], FormCodeEntry] = {")
    for rec in records:
        ordinance_code = rec["ordinance_code"] or ""
        form_code = rec["form_code"] or ""
        lines.append(
            f"    ({_to_py(ordinance_code)}, {_to_py(form_code)}): FormCodeEntry("
        )
        lines.append(f"        ordinance_code={_to_py(ordinance_code)},")
        lines.append(f"        form_code={_to_py(form_code)},")
        lines.append(f"        form_number={_to_py(rec['form_number'])},")
        lines.append(f"        form_name={_to_py(rec['form_name'])},")
        lines.append(f"        doc_type_name={_to_py(rec['doc_type_name'])},")
        lines.append(f"        disclosure_type={_to_py(rec['disclosure_type'])},")
        lines.append(f"        note={_to_py(rec['note'])},")
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    lines.append("FORM_CODE_RECORD_COUNT = len(_FORM_CODE_TABLE)")
    lines.append("")
    lines.append("_warned_unknown_form_codes: set[tuple[str, str]] = set()")
    lines.append("")
    lines.append("")
    lines.append("def get_form_code(ordinance_code: str, form_code: str) -> FormCodeEntry | None:")
    lines.append('    """府令コードと様式コードのペアから FormCodeEntry を返す。"""')
    lines.append("    key = (ordinance_code, form_code)")
    lines.append("    entry = _FORM_CODE_TABLE.get(key)")
    lines.append("    if entry is None and key not in _warned_unknown_form_codes:")
    lines.append("        _warned_unknown_form_codes.add(key)")
    lines.append("        warnings.warn(")
    lines.append('            f"Unknown formCode: ordinance={ordinance_code!r}, form={form_code!r}. ",')
    lines.append('            category=EdinetWarning,')
    lines.append("            stacklevel=2,")
    lines.append("        )")
    lines.append("    return entry")
    lines.append("")
    lines.append("")
    lines.append("def all_form_codes() -> list[FormCodeEntry]:")
    lines.append('    """全様式コードの一覧を返す。"""')
    lines.append("    return list(_FORM_CODE_TABLE.values())")
    lines.append("")
    lines.append("")
    lines.append("def _reset_warning_state() -> None:")
    lines.append('    """テスト用。"""')
    lines.append("    _warned_unknown_form_codes.clear()")
    lines.append("")
    return "\n".join(lines)


def generate(source: Path, output: Path) -> int:
    records = load_form_records(source)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_form_module(records, source.as_posix()), encoding="utf-8")
    return len(records)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("data/source/ESE140327.xlsx"),
        help="Path to ESE140327.xlsx",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/edinet/models/form_code.py"),
        help="Path to generated form_code.py",
    )
    args = parser.parse_args()

    count = generate(args.source, args.output)
    print(f"Generated {args.output} with {count} records.")


if __name__ == "__main__":
    main()
